### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by niandrei** [watchowl/cake-scheduler#2]
I'm using CakePhp 3.5.6 and installed this plugin with Composer.
I have added 'Plugin::load('Watchowl/CakeScheduler');' to my config/bootstrap.php file.

I get this error:

> Error: The application is trying to load a file from the Watchowl/CakeScheduler plugin. 
> Make sure your plugin Watchowl/CakeScheduler is in the /var/www/intranet/cakephp/plugins/ directory and was loaded.

I have found the plugin in the 'vendor' folder, not 'plugins', where CakePhp is looking for it.

**Comment by fiste788** [comment]
same problem here. fixed with this change
`Plugin::load('Watchowl/CakeScheduler');`
to
`Plugin::load('WatchOwl/CakeScheduler');`

**Comment by watchowl** [comment]
Fixed.
